# Site settings
title: Title
author:
  name: Gaëtan Andrieu
  email: your-email@domain.com
  github_username:  gaetanandrieu

description: "This is a descrition."

# Build settings
remote_theme: jekyll/minima
